In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import log_loss
from sklearn.model_selection import StratifiedKFold, cross_val_score, KFold
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

In [2]:
df = pd.read_csv("train_Santander.csv")
df

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76015,151829,2,48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60926.490000,0
76016,151830,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118634.520000,0
76017,151835,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74028.150000,0
76018,151836,2,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84278.160000,0
76019,151838,2,46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [3]:
testdf = pd.read_csv("test_Santander.csv")
testdf

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
0,2,2,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40532.100000
1,5,2,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45486.720000
2,6,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46993.950000
3,7,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,187898.610000
4,9,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73649.730000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75813,151831,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40243.200000
75814,151832,2,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,146961.300000
75815,151833,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,167299.770000
75816,151834,2,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016
75817,151837,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016

In [4]:
y = df["TARGET"]
X = df.drop(['TARGET'], axis = 1)
X_test = testdf

In [ ]:
std_scaler = StandardScaler().set_output(transform='pandas')
std_mm = MinMaxScaler()
rf = RandomForestClassifier()
prcomp = PCA().set_output(transform='pandas')

pipe = Pipeline([('SCL', std_mm), ('PCA',prcomp),('RF', rf)])


kfold = KFold(n_splits = 5, shuffle = True, random_state=24)
params = {'PCA__n_components': np.arange(6,12),'SCL':[std_scaler, std_mm, None], 'RF__max_depth':[2,3] }
gcv = GridSearchCV(pipe, param_grid = params, cv = kfold, scoring = 'roc_auc', refit=True)
gcv.fit(X, y)
print(gcv.best_score_)
print(gcv.best_params_)

y_pred_prob = gcv.predict_proba(X_test)
y_pred_prob = y_pred_prob[:,1]

submit = pd.DataFrame({'ID':list(testdf.index), 'TARGET': y_pred_prob})
submit

In [ ]:
#XGBoost

std_scaler = StandardScaler().set_output(transform='pandas')
std_mm = MinMaxScaler()
xgb=XGBClassifier(random_state=24)
prcomp = PCA().set_output(transform='pandas')

pipe = Pipeline([('SCL', std_mm), ('PCA',prcomp),('XGB', xgb)])
#pipe.fit(X, y)

kfold = KFold(n_splits = 5, shuffle = True, random_state=24)
params = {'PCA__n_components': np.arange(6,12),'SCL':[std_scaler, std_mm, None], 
          'XGB__max_depth':[2,3], 'XGB__learning_rate': np.linspace(0.001, 0.9, 10),'XGB__n_estimators': [25, 50, 100]}
gcv = GridSearchCV(pipe, param_grid = params, cv = kfold, scoring = 'roc_auc', refit=True)
gcv.fit(X, y)
print(gcv.best_score_)
print(gcv.best_params_)

y_pred_prob = gcv.predict_proba(X_test)
y_pred_prob = y_pred_prob[:,1]

submit = pd.DataFrame({'ID':list(testdf.index), 'TARGET': y_pred_prob})
submit

In [ ]:
# catboost with gcv but no para

#CatBoost

std_scaler = StandardScaler().set_output(transform='pandas')
std_mm = MinMaxScaler()
cb = CatBoostClassifier(random_state=24)
prcomp = PCA().set_output(transform='pandas')

pipe = Pipeline([('SCL', std_mm), ('PCA',prcomp),('CAT', cb)])
#pipe.fit(X, y)

kfold = KFold(n_splits = 5, shuffle = True, random_state=24)
params = {'PCA__n_components': np.arange(6,12),'SCL':[std_scaler, std_mm, None]}

gcv = GridSearchCV(pipe, param_grid = params, cv = kfold, scoring = 'roc_auc', refit=True)
gcv.fit(X, y)
print(gcv.best_score_)
print(gcv.best_params_)

y_pred_prob = gcv.predict_proba(X_test)
y_pred_prob = y_pred_prob[:,1]

submit = pd.DataFrame({'ID':list(testdf.index), 'TARGET': y_pred_prob})
submit

In [ ]:
# lgmb without gcv

#LGBM

std_scaler = StandardScaler().set_output(transform='pandas')
std_mm = MinMaxScaler()
lgb = LGBMClassifier(random_state=24)
prcomp = PCA().set_output(transform='pandas')

pipe = Pipeline([('SCL', std_mm), ('PCA',prcomp),('LGBM', lgb)])
pipe.fit(X, y)

y_pred_prob = pipe.predict_proba(X_test)
y_pred_prob = y_pred_prob[:,1]

submit = pd.DataFrame({'ID':list(testdf.index), 'TARGET': y_pred_prob})
submit