In [14]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
# Find out how many principal components explain more than 90% variation taking all the variables except ID and target.

In [7]:
df = pd.read_csv("train_Santander.csv")
df

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76015,151829,2,48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60926.490000,0
76016,151830,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118634.520000,0
76017,151835,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74028.150000,0
76018,151836,2,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84278.160000,0
76019,151838,2,46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [8]:
testdf = pd.read_csv("test_Santander.csv",index_col = 0)
testdf

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
ID,,,,,,,,,,,,,,,,,,,,,
2,2,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40532.100000
5,2,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45486.720000
6,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46993.950000
7,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,187898.610000
9,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73649.730000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151831,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40243.200000
151832,2,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,146961.300000
151833,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,167299.770000
151834,2,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016
151837,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016

In [9]:
df["TARGET"].unique()

array([0, 1], dtype=int64)

In [10]:
# define X and y

X = df.drop(["TARGET"],axis = 1)
y = df["TARGET"]

In [11]:

X_train, y_train, X_test, y_test = train_test_split(X,y,random_state = 24, test_size=0.3)

In [12]:
lr = LogisticRegression()

In [15]:
scaler  = StandardScaler().set_output(transform='pandas')
scaler.fit(X)
X_scaled = scaler.transform(X)

In [16]:
pca = PCA().set_output(transform = "pandas")
p_comps = pca.fit_transform(X_scaled)

pc_cumsum = np.cumsum(pca.explained_variance_ratio_ * 100)
pc_cumsum

array([  8.05763633,  13.27101621,  16.90409613,  20.37253906,
        23.77691459,  26.88604482,  29.81857095,  32.63425181,
        35.23636482,  37.78998334,  40.03787743,  42.16369842,
        44.26731254,  46.30556282,  48.2876837 ,  50.03329713,
        51.66047482,  53.21426381,  54.60109275,  55.91966591,
        57.20768309,  58.43882106,  59.65903327,  60.83590105,
        61.90891688,  62.96608702,  63.9941105 ,  65.0018893 ,
        65.99665756,  66.9581658 ,  67.90670798,  68.83904655,
        69.75112211,  70.62239907,  71.46660649,  72.26749578,
        73.00181718,  73.7151255 ,  74.38973643,  75.0544306 ,
        75.69940115,  76.3229047 ,  76.94483606,  77.55014487,
        78.14909683,  78.74609883,  79.32565026,  79.90117111,
        80.46896414,  81.01984623,  81.5394037 ,  82.04722021,
        82.48770475,  82.92039854,  83.33813542,  83.74832662,
        84.15427425,  84.54340894,  84.92516215,  85.29526777,
        85.66049125,  86.01578759,  86.37003391,  86.70005493,
        87.02321587,  87.33157594,  87.63317507,  87.93184185,
        88.22861227,  88.52388262,  88.81698364,  89.09931534,
        89.37670131,  89.65259412,  89.91768842,  90.17254719,
        90.4237022 ,  90.66943045,  90.91192609,  91.1482763 ,
        91.3764225 ,  91.60301414,  91.82371377,  92.04117723,
        92.2566976 ,  92.46800663,  92.6761533 ,  92.8795515 ,
        93.08139429,  93.27900927,  93.47454676,  93.66858596,
        93.85601293,  94.03756172,  94.21513341,  94.37810737,
        94.5407532 ,  94.69434738,  94.84065417,  94.9824552 ,
        95.11986514,  95.25371604,  95.38623372,  95.51565306,
        95.64259175,  95.76741545,  95.88802643,  96.00798811,
        96.12393707,  96.23766763,  96.34930146,  96.46039221,
        96.56914132,  96.6732539 ,  96.77619304,  96.87872386,
        96.97338649,  97.06619579,  97.15803711,  97.24960276,
        97.34051073,  97.43048332,  97.52022163,  97.60504985,
        97.68770193,  97.76964652,  97.84856241,  97.92471537,
        97.99902136,  98.06856282,  98.13682645,  98.20241167,
        98.26759248,  98.33098247,  98.39276344,  98.45372664,
        98.51396321,  98.57206248,  98.62856288,  98.68416413,
        98.73858096,  98.79066064,  98.84219504,  98.89252609,
        98.94187719,  98.99092187,  99.03928669,  99.08307482,
        99.12326122,  99.160606  ,  99.196161  ,  99.23033698,
        99.26419046,  99.29729071,  99.32924036,  99.35888888,
        99.38748156,  99.41452993,  99.44045099,  99.46570915,
        99.49045688,  99.51415705,  99.5364593 ,  99.55858893,
        99.58004638,  99.60100683,  99.62170081,  99.64182252,
        99.6618373 ,  99.68152691,  99.70027269,  99.7185953 ,
        99.73575183,  99.7518884 ,  99.76775174,  99.7832411 ,
        99.79744035,  99.8111141 ,  99.82474042,  99.83766926,
        99.84952993,  99.86004197,  99.86920761,  99.87812615,
        99.88625261,  99.89375394,  99.90094309,  99.90786577,
        99.91456095,  99.92035764,  99.92613025,  99.93159827,
        99.93702943,  99.94216127,  99.94705477,  99.95187353,
        99.95607282,  99.95996249,  99.96346869,  99.9667121 ,
        99.96978526,  99.97239751,  99.97485617,  99.97706192,
        99.97915755,  99.98120328,  99.9831428 ,  99.9848719 ,
        99.98645898,  99.9879858 ,  99.98926474,  99.99051289,
        99.99163611,  99.99274884,  99.99369485,  99.99456517,
        99.99540283,  99.99606106,  99.99671113,  99.99729704,
        99.9977961 ,  99.99819163,  99.99852713,  99.99886018,
        99.99912518,  99.99928959,  99.99944544,  99.99959092,
        99.99972899,  99.99983132,  99.99989838,  99.99996505,
        99.99998766, 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        ])

In [17]:
#a. Finding out how many principal components explain more than 90% variation  
print((len(pc_cumsum)- (pc_cumsum > 90).sum()) + 1 )

76

In [19]:
y_pred = pca.predict(X_test)

AttributeError: 'PCA' object has no attribute 'pred'

In [6]:
res = pd.DataFrame({"id": list(testdf.index), "target":y_pred })
res.to_csv("Santander_pca.csv", index = False)

NameError: name 'testdf' is not defined